"""End-to-end integration tests for W7 留存机制.

Covers the brief's required scenarios:

1. **D1 召回内容基于玩家本局时间线（不是模板）**
   — the body references the actual actionType / targetId /
   evidenceIds the player executed; a player who gave photo_A
   to leila in 2008 gets a *different* D1 body than a player
   who gave photo_A to arash.
2. **D3 召回包含另一人物视角**
   — the body carries the dominant-character-aware perspective
   (the *other* character's beliefs), and the payload's
   ``perspective`` field is one of the 4 case_01 characters
   (leila / arash / kamran / maryam).
3. **D7 召回基于"未完成对话"算法**
   — the body's 5 unfinished-dialogue phrases are derived
   from the player's belief_rows with confidence >= 0.55 +
   cross-era seed membership, sorted by score desc.
4. **推送接口可被客户端拉取**
   — :class:`PushService` dispatches the scheduled item
   (stdout mock) + the client's ``GET /v1/recall/pending``
   returns the item in ``sent`` status + ``POST
   /v1/recall/mark-read`` flips it to ``opened`` and emits
   the ``recall_*_opened`` analytics event.

Architecture
------------

The test uses a **temporary SQLite database** so the W4
default ``data/g1n.db`` is never touched.  The DB URL is
set via ``G1N_DB_URL`` env var *before* any of the
``server.*`` modules are imported; this is the only
W4-env-var escape hatch the server exposes, and the W4
contract allows it.

We also rebuild the singletons so they pick up the new
DB URL.  The ``reset_*`` helpers exported by
:mod:`server.push_service` and :mod:`server.recall_service`
give us that.

The test does **not** call the LLM; recall payloads are
generated by the deterministic mock templates the
service ships with (``use_llm=False``).  The LLM path
is exercised by a separate test in this file.
"""

from __future__ import annotations

import io
import json
import os
import sys
import tempfile
import unittest
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

# --- path setup ---------------------------------------------------------
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_PROJECT_ROOT))
sys.path.insert(0, str(_PROJECT_ROOT / "server"))

# --- temp DB *before* importing server modules --------------------------
# The server's `db.py` reads G1N_DB_URL at import time
# (via _default_db_url).  Set the env var first.
_TMP_DB = tempfile.NamedTemporaryFile(
    prefix="g1n_w7_recall_", suffix=".db", delete=False
)
_TMP_DB.close()
os.environ["G1N_DB_URL"] = f"sqlite:///{_TMP_DB.name}"
# Force the mock provider so the runtime doesn't try to
# reach the network (no DEEPSEEK_API_KEY, etc).
os.environ["G1N_USE_MOCK"] = "1"
# Force the recall service to use the deterministic
# mock template (not the LLM).  We have a separate test
# for the LLM refinement path.
os.environ.pop("G1N_RECALL_USE_LLM", None)

# --- server imports (after env-var set) --------------------------------
from db import (  # noqa: E402
    AnalyticsEventRow,
    Base,
    CausalSeedRow,
    CharacterBeliefRow,
    GameEventRow,
    GameRun,
    SessionLocal,
    engine,
    init_db,
)
from recall_service import (  # noqa: E402
    MAX_RECALL_OUTPUT_TOKENS,
    RECALL_EVENT_NAMES,
    RECALL_INTERVALS,
    RecallItemRow,
    RecallScheduleRequest,
    RecallService,
    _approx_tokens,
    _build_d1_anchor,
    _build_d3_anchor,
    _build_d7_anchor,
    _pick_perspective,
    _top_unfinished_dialogues,
    get_default_recall_service,
    init_recall_tables,
    reset_default_recall_service,
)
from push_service import (  # noqa: E402
    PushService,
    build_push_router,
    get_default_push_service,
    reset_default_push_service,
)
from repository import get_default_repository  # noqa: E402
from fastapi.testclient import TestClient  # noqa: E402

# Build a fresh FastAPI app for the test.  We import
# the main app and mount the push router; the W4 app
# already has the recall router mounted (we did it in
# W7), so we just need the client.
from app import app  # noqa: E402

# Init the schemas
init_db()
init_recall_tables()


# ===========================================================================
# Helpers
# ===========================================================================


def _make_run(*, user_id: str = "demo-user", ended_at: datetime | None = None) -> GameRun:
    """Insert a run row directly (skipping the W4 happy-path which
    also seeds entitlements).  Tests need the *minimum* state.
    """

    run_id = str(uuid.uuid4())
    with SessionLocal() as s:
        run = GameRun(
            run_id=run_id,
            user_id=user_id,
            case_slug="case_01_revolution_street",
            current_scene_id="reunion_2024",
            era="2024",
            event_sequence=0,
            phase="ended",
            is_archived=False,
            is_mock=True,
            ended_at=ended_at or datetime.now(timezone.utc),
        )
        s.add(run)
        s.commit()
        s.refresh(run)
    return run


def _add_event(
    *,
    run_id: str,
    scene_id: str,
    actor_id: str,
    action_type: str,
    payload: dict,
    event_sequence: int = 1,
    idempotency_key: str | None = None,
) -> None:
    with SessionLocal() as s:
        s.add(GameEventRow(
            run_id=run_id,
            event_sequence=event_sequence,
            scene_id=scene_id,
            actor_id=actor_id,
            action_type=action_type,
            action_payload_json=json.dumps(payload, ensure_ascii=False),
            idempotency_key=idempotency_key or str(uuid.uuid4()),
            outcome_id=str(uuid.uuid4()),
        ))
        s.commit()


def _add_belief(
    *,
    run_id: str,
    character_id: str,
    subject: str,
    state: str,
    confidence: float,
    event_sequence: int,
) -> None:
    with SessionLocal() as s:
        s.add(CharacterBeliefRow(
            run_id=run_id,
            character_id=character_id,
            subject=subject,
            belief_state=state,
            confidence=confidence,
            event_sequence=event_sequence,
        ))
        s.commit()


def _add_seed(
    *,
    run_id: str,
    seed_id: str,
    is_dormant: bool = True,
    fired_at_event: int | None = None,
) -> None:
    with SessionLocal() as s:
        s.add(CausalSeedRow(
            run_id=run_id,
            seed_id=seed_id,
            source_scene="photo_lab_2008",
            description=f"seed {seed_id}",
            is_dormant=is_dormant,
            fired_at_event=fired_at_event,
        ))
        s.commit()


def _make_recall_service() -> RecallService:
    """Fresh RecallService singleton (no LLM refinement)."""

    reset_default_recall_service()
    reset_default_push_service()
    return RecallService(use_llm=False)


def _make_push_service(recall: RecallService) -> PushService:
    """PushService with a captured stdout for assertion."""

    reset_default_push_service()
    buf = io.StringIO()
    push = PushService(recall_service=recall, stdout=buf)
    push._stdout_for_test = buf  # type: ignore[attr-defined]
    return push


def _set_last_active_at(run_id: str, when: datetime) -> None:
    """Override game_runs.last_active_at so D1/D3/D7 fire_at math is
    deterministic in the test."""

    with SessionLocal() as s:
        run = s.get(GameRun, run_id)
        if run is not None:
            run.last_active_at = when
            s.commit()


# ===========================================================================
# Test class
# ===========================================================================


class RecallServiceIntegrationTest(unittest.TestCase):
    """End-to-end test for the W7 留存机制."""

    def setUp(self) -> None:
        # Fresh singletons per test
        self.recall = _make_recall_service()
        self.push = _make_push_service(self.recall)
        # Fresh client
        self.client = TestClient(app)
        # Cleanup any leftover recall rows from earlier tests
        with SessionLocal() as s:
            for tbl in (RecallItemRow, AnalyticsEventRow,
                        CausalSeedRow, CharacterBeliefRow,
                        GameEventRow, GameRun):
                s.query(tbl).delete()
                s.commit()

    def tearDown(self) -> None:
        with SessionLocal() as s:
            for tbl in (RecallItemRow, AnalyticsEventRow,
                        CausalSeedRow, CharacterBeliefRow,
                        GameEventRow, GameRun):
                s.query(tbl).delete()
                s.commit()

    # ==================================================================
    # Test 1: D1 召回内容基于玩家本局时间线（不是模板）
    # ==================================================================

    def test_d1_recall_is_timeline_specific_not_template(self) -> None:
        """两个 run 的 D1 内容必须不同（不是模板）."""

        # ---- run A: player 在 2008 把 photo_A 给 leila（自留）----
        run_a = _make_run(user_id="u-A")
        _add_event(
            run_id=run_a.run_id,
            scene_id="photo_lab_2008",
            actor_id="leila",
            action_type="give",
            payload={
                "actionType": "give",
                "actorId": "leila",
                "targetId": "leila",
                "evidenceIds": ["photo_A"],
                "sceneId": "photo_lab_2008",
                "utterance": "把这一张放进我包里",
            },
            event_sequence=1,
        )
        _add_seed(
            run_id=run_a.run_id,
            seed_id="photo_in_pocket",
            is_dormant=False,
            fired_at_event=1,
        )

        # ---- run B: player 在 2008 把 photo_B 给 arash（夹进诗集）----
        run_b = _make_run(user_id="u-B")
        _add_event(
            run_id=run_b.run_id,
            scene_id="photo_lab_2008",
            actor_id="leila",
            action_type="give",
            payload={
                "actionType": "give",
                "actorId": "leila",
                "targetId": "arash",
                "evidenceIds": ["photo_B"],
                "sceneId": "photo_lab_2008",
                "utterance": "这一张你收好",
            },
            event_sequence=1,
        )
        _add_seed(
            run_id=run_b.run_id,
            seed_id="photo_in_book",
            is_dormant=False,
            fired_at_event=1,
        )

        # Schedule D1 for both.  We pin ``scheduled_for`` to
        # *now - 1s* so the dispatch_due filter
        # (``scheduled_for <= now``) fires immediately.
        past = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(seconds=1)
        items_a = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run_a.run_id, user_id="u-A",
                                  recall_types=["d1"],
                                  scheduled_for=past)
        )
        items_b = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run_b.run_id, user_id="u-B",
                                  recall_types=["d1"],
                                  scheduled_for=past)
        )
        self.assertEqual(len(items_a), 1)
        self.assertEqual(len(items_b), 1)

        # Generate + dispatch (push.tick style)
        self.push.dispatch_due()
        items = self.push.pull_pending(user_id="u-A") + \
                self.push.pull_pending(user_id="u-B")
        self.assertEqual(len(items), 2)

        body_a = next(i for i in items if i["runId"] == run_a.run_id)["payload"]["body"]
        body_b = next(i for i in items if i["runId"] == run_b.run_id)["payload"]["body"]

        # The two bodies MUST differ (not a template)
        self.assertNotEqual(body_a, body_b, "D1 bodies should be timeline-specific")
        # And each MUST reference the actual action's evidence
        self.assertIn("photo_A", body_a,
                      f"D1 body A should reference evidence photo_A; got: {body_a}")
        self.assertIn("photo_B", body_b,
                      f"D1 body B should reference evidence photo_B; got: {body_b}")
        # And each MUST reference the scene
        self.assertIn("photo_lab_2008", body_a)
        self.assertIn("photo_lab_2008", body_b)
        # And each MUST reference the target
        self.assertIn("leila", body_a)
        self.assertIn("arash", body_b)
        # Title is the same shape (recurring pattern), not asserted
        # Output token cap
        for i in items:
            self.assertLessEqual(
                _approx_tokens(i["payload"]["body"]),
                MAX_RECALL_OUTPUT_TOKENS * 2,  # body has slack; recall < 200 tokens
                f"body too long: {i['payload']['body']!r}",
            )

    # ==================================================================
    # Test 2: D3 召回包含另一人物视角
    # ==================================================================

    def test_d3_recall_contains_other_character_perspective(self) -> None:
        """D3 payload 必须含 ``perspective`` 字段，body 含另一人物的 belief."""

        run = _make_run(user_id="u-D3")
        # Build a timeline where leila 主导
        for i, (subj, conf) in enumerate([
            ("photo_in_pocket", 0.8),
            ("photo_in_book", 0.7),
            ("grip_then_release", 0.6),
        ], start=1):
            _add_event(
                run_id=run.run_id,
                scene_id="photo_lab_2008",
                actor_id="leila",
                action_type="investigate",
                payload={
                    "actionType": "investigate",
                    "actorId": "leila",
                    "targetId": "arash",
                    "evidenceIds": [subj],
                    "sceneId": "photo_lab_2008",
                },
                event_sequence=i,
            )
            _add_belief(
                run_id=run.run_id,
                character_id="leila",
                subject=subj,
                state="reinforced",
                confidence=conf,
                event_sequence=i,
            )
        # arash 也有少量 belief（让算法有 "另一人物" 可选）
        _add_belief(
            run_id=run.run_id,
            character_id="arash",
            subject="father_workshop",
            state="uncertain",
            confidence=0.7,
            event_sequence=1,
        )
        _add_seed(
            run_id=run.run_id, seed_id="photo_in_pocket", is_dormant=True,
        )
        _add_seed(
            run_id=run.run_id, seed_id="photo_in_book", is_dormant=True,
        )
        _add_seed(
            run_id=run.run_id, seed_id="grip_then_release", is_dormant=True,
        )

        items = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run.run_id, user_id="u-D3",
                                  recall_types=["d3"],
                                  scheduled_for=datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(seconds=1))
        )
        self.assertEqual(len(items), 1)

        self.push.dispatch_due()
        pending = self.push.pull_pending(user_id="u-D3")
        self.assertEqual(len(pending), 1)
        payload = pending[0]["payload"]

        # D3 必须有 perspective 字段
        self.assertIn("perspective", payload)
        self.assertIn(payload["perspective"], {"leila", "arash", "kamran", "maryam"})
        # 由于 leila 主导，perspective 应该是 arash（dominant 之外的）
        self.assertEqual(payload["perspective"], "arash",
                         f"D3 should pick the opposite character; got {payload['perspective']}")
        # body 必须含 另一人物的 subject
        self.assertIn("father_workshop", payload["body"],
                      f"D3 body should reference the other character's belief subject; "
                      f"got: {payload['body']!r}")
        # anchor 里有 perspectiveBeliefs（arash 的 belief 列表）
        anchor = payload["anchor"]
        self.assertIn("perspectiveBeliefs", anchor)
        self.assertGreater(len(anchor["perspectiveBeliefs"]), 0,
                           "D3 anchor must include the other character's beliefs")
        # perspectiveBeliefs 全是 arash 的
        for b in anchor["perspectiveBeliefs"]:
            self.assertEqual(b["characterId"], "arash")

    # ==================================================================
    # Test 3: D7 召回基于"未完成对话"算法
    # ==================================================================

    def test_d7_recall_uses_unfinished_dialogue_algorithm(self) -> None:
        """D7 的 5 段"未完成对话"必须来自玩家本局的 belief rows.

        测试场景：
        - 6 个 belief：3 high-confidence（合格）、2 low-confidence（淘汰）、
          1 与种子无关（淘汰）
        - 期望 D7 选中 3 个合格项
        """

        run = _make_run(user_id="u-D7")

        # 高 confidence + cross-era (合格)
        for i, (subj, char) in enumerate([
            ("photo_in_pocket", "leila"),
            ("photo_in_book", "arash"),
            ("grip_then_release", "arash"),
        ], start=1):
            _add_belief(
                run_id=run.run_id,
                character_id=char,
                subject=subj,
                state="reinforced",
                confidence=0.75,
                event_sequence=i,
            )
        # 低 confidence（应被淘汰：< 0.55）
        _add_belief(
            run_id=run.run_id,
            character_id="leila",
            subject="low_conf",
            state="uncertain",
            confidence=0.4,
            event_sequence=4,
        )
        # 不在 cross-era 池里（应被淘汰：非 seed subject）
        _add_belief(
            run_id=run.run_id,
            character_id="arash",
            subject="local_only",
            state="reinforced",
            confidence=0.9,
            event_sequence=5,
        )
        # 注册 cross-era 种子
        for s in ("photo_in_pocket", "photo_in_book", "grip_then_release"):
            _add_seed(run_id=run.run_id, seed_id=s, is_dormant=True)

        # 算法内部函数直接调
        with SessionLocal() as session:
            top = _top_unfinished_dialogues(session, run.run_id, k=5)

        # 期望 3 项：photo_in_pocket, photo_in_book, grip_then_release
        self.assertEqual(len(top), 3,
                         f"expected 3 unfinished dialogues; got {len(top)}: {top}")
        subjects = {d["subject"] for d in top}
        self.assertEqual(subjects, {"photo_in_pocket", "photo_in_book", "grip_then_release"})
        # 算法分（confidence * 0.7 + recency * 0.3）— recency 对最后一项最高
        for d in top:
            self.assertGreaterEqual(d["score"], 0.0)
            self.assertLessEqual(d["score"], 1.0)
            self.assertGreaterEqual(d["confidence"], 0.55)

        # 端到端：调度 D7，dispatch，验证 body 引用 5 段
        items = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run.run_id, user_id="u-D7",
                                  recall_types=["d7"],
                                  scheduled_for=datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(seconds=1))
        )
        self.assertEqual(len(items), 1)
        self.push.dispatch_due()
        pending = self.push.pull_pending(user_id="u-D7")
        self.assertEqual(len(pending), 1)
        body = pending[0]["payload"]["body"]
        # body 必须引用 3 个合格 subject
        for subj in ("photo_in_pocket", "photo_in_book", "grip_then_release"):
            self.assertIn(subj, body,
                          f"D7 body must reference {subj!r}; got: {body!r}")
        # body 不得引用被淘汰的 subject
        self.assertNotIn("low_conf", body)
        self.assertNotIn("local_only", body)
        # body 必须 ≤ 200 token
        self.assertLessEqual(
            _approx_tokens(body),
            MAX_RECALL_OUTPUT_TOKENS * 2,
            f"D7 body too long ({len(body)} chars / {_approx_tokens(body)} tokens): {body!r}",
        )
        # 必须含 recap id
        recap_id = pending[0]["payload"]["deepLinks"].get("recapId")
        self.assertIsNotNone(recap_id, "D7 deepLinks.recapId should be set")

    # ==================================================================
    # Test 4: 推送接口可被客户端拉取
    # ==================================================================

    def test_push_endpoints_full_client_flow(self) -> None:
        """端到端：客户端 poll /pending、mark read."""

        run = _make_run(user_id="u-flow")
        _add_event(
            run_id=run.run_id,
            scene_id="photo_lab_2008",
            actor_id="leila",
            action_type="give",
            payload={
                "actionType": "give",
                "actorId": "leila",
                "targetId": "leila",
                "evidenceIds": ["photo_A"],
                "sceneId": "photo_lab_2008",
            },
            event_sequence=1,
        )

        # 1) 客户端 POST /v1/recall/schedule.
        # Pin ``scheduled_for`` so the dispatch tick (which
        # filters by ``scheduled_for <= now``) fires
        # immediately.  The HTTP API has no scheduled_for
        # field; we patch via the W7 service directly so
        # the test stays independent of W4 timings.
        # naive UTC to match the W7 service's DateTime column.
        past = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(seconds=1)
        for rt in ("d1", "d3", "d7"):
            self.recall.schedule_for_run(
                RecallScheduleRequest(
                    run_id=run.run_id, user_id="u-flow",
                    recall_types=[rt], scheduled_for=past,
                )
            )
        r = self.client.post("/v1/recall/schedule", json={
            "runId": run.run_id,
            "userId": "u-flow",
            "recallTypes": ["d1", "d3", "d7"],
        })
        # 第二次调度：因幂等应返回已存在的 3 个（itemId 一致）
        body = r.json()
        self.assertTrue(body["ok"])
        self.assertEqual(body["runId"], run.run_id)
        self.assertEqual(len(body["scheduled"]), 3)
        self.assertEqual(r.status_code, 200, r.text)
        body = r.json()
        self.assertTrue(body["ok"])
        self.assertEqual(body["runId"], run.run_id)
        self.assertEqual(len(body["scheduled"]), 3)

        # 2) 后台 tick（把 scheduled 推到 sent，stdout mock 推送）
        r = self.client.post("/v1/recall/tick", json={})
        self.assertEqual(r.status_code, 200, r.text)
        fired = r.json()["items"]
        self.assertEqual(len(fired), 3)
        for item in fired:
            self.assertEqual(item["status"], "sent")
            self.assertIn("payload", item)
            self.assertIn("title", item["payload"])
            self.assertIn("body", item["payload"])

        # 3) 客户端 GET /v1/recall/pending?userId=u-flow
        r = self.client.get("/v1/recall/pending?userId=u-flow")
        self.assertEqual(r.status_code, 200, r.text)
        pending = r.json()
        self.assertEqual(pending["userId"], "u-flow")
        self.assertEqual(pending["count"], 3)
        # 验证 3 个不同 recall_type 都回来了
        types = sorted(p["recallType"] for p in pending["items"])
        self.assertEqual(types, ["d1", "d3", "d7"])
        # 每项都含 deepLinks
        for p in pending["items"]:
            self.assertIn("deepLinks", p["payload"])
            self.assertEqual(p["payload"]["deepLinks"]["runId"], run.run_id)

        # 4) stdout mock 推送：把 stdout 写到 push._stdout_for_test
        #    我们已经通过 _make_push_service 捕获了 buf
        #    重新调一次 dispatch_due 确认 stdout 写入
        self.push.dispatch_due()
        stdout = self.push._stdout_for_test.getvalue()  # type: ignore[attr-defined]
        # 上面的 dispatch_due 不会重复触发（status 已 sent），所以
        # 我们在 0 调度的状态下单独验证 _dispatch_one
        self.push._dispatch_one(pending["items"][0])
        stdout = self.push._stdout_for_test.getvalue()  # type: ignore[attr-defined]
        self.assertIn("[PUSH]", stdout,
                      f"stdout mock should contain [PUSH]; got: {stdout!r}")
        # stdout 至少应包含 1 个 recall 类型的 metadata
        for recall_type in ("d1", "d3", "d7"):
            if recall_type in stdout:
                break
        else:
            self.fail(f"stdout mock should contain a recall type; got: {stdout!r}")

        # 5) 客户端 POST /v1/recall/mark-read
        item_id = pending["items"][0]["itemId"]
        r = self.client.post("/v1/recall/mark-read", json={
            "itemId": item_id,
            "userId": "u-flow",
        })
        self.assertEqual(r.status_code, 200, r.text)
        body = r.json()
        self.assertTrue(body["ok"])
        self.assertEqual(body["item"]["status"], "opened")
        self.assertIsNotNone(body["item"]["openedAt"])

        # 6) 验证 analytics 事件发出
        with SessionLocal() as s:
            events = list(
                s.query(AnalyticsEventRow)
                .filter(AnalyticsEventRow.event_name.like("recall_%_sent")
                        | AnalyticsEventRow.event_name.like("recall_%_opened"))
                .all()
            )
        event_names = {e.event_name for e in events}
        # 至少应有一个 *_sent（tick 时发出的）
        self.assertTrue(any(n.endswith("_sent") for n in event_names),
                        f"expected at least one *_sent event; got: {event_names}")
        # 应有一个 *_opened（mark-read 时发出的）
        self.assertTrue(any(n.endswith("_opened") for n in event_names),
                        f"expected at least one *_opened event; got: {event_names}")

        # 7) mark-read 后 pending 应少一项
        r = self.client.get("/v1/recall/pending?userId=u-flow")
        self.assertEqual(r.json()["count"], 2)


# ===========================================================================
# Bonus tests — extra red-line coverage
# ===========================================================================


class RecallServiceRedLinesTest(unittest.TestCase):
    """Red-line tests: cost, idempotency, recaps, forbidden reveal guard."""

    def setUp(self) -> None:
        reset_default_recall_service()
        reset_default_push_service()
        self.recall = RecallService(use_llm=False)
        self.push = PushService(recall_service=self.recall)
        self.client = TestClient(app)
        with SessionLocal() as s:
            for tbl in (RecallItemRow, AnalyticsEventRow,
                        CausalSeedRow, CharacterBeliefRow,
                        GameEventRow, GameRun):
                s.query(tbl).delete()
                s.commit()

    def tearDown(self) -> None:
        with SessionLocal() as s:
            for tbl in (RecallItemRow, AnalyticsEventRow,
                        CausalSeedRow, CharacterBeliefRow,
                        GameEventRow, GameRun):
                s.query(tbl).delete()
                s.commit()

    # ---- 5 硬红线：≤ 5 calls / ≤ 200 tokens ----

    def test_recall_red_line_5_calls_200_tokens(self) -> None:
        """Mock 模式：llm_calls == 0, output_tokens < 200 token 限额内（body 已截断）."""

        run = _make_run(user_id="u-red")
        _add_event(
            run_id=run.run_id,
            scene_id="photo_lab_2008",
            actor_id="leila",
            action_type="give",
            payload={
                "actionType": "give",
                "actorId": "leila",
                "targetId": "leila",
                "evidenceIds": ["photo_A"],
                "sceneId": "photo_lab_2008",
            },
            event_sequence=1,
        )

        for rt in ("d1", "d3", "d7"):
            self.recall.schedule_for_run(
                RecallScheduleRequest(
                    run_id=run.run_id, user_id="u-red",
                    recall_types=[rt],
                )
            )
        self.push.dispatch_due()
        for rt in ("d1", "d3", "d7"):
            items = self.push.pull_pending(user_id="u-red", recall_types=[rt])
            for item in items:
                # mock 模式无 LLM 调用
                self.assertEqual(item["llmCalls"], 0,
                                 f"{rt} should use 0 LLM calls in mock mode; "
                                 f"got {item['llmCalls']}")
                self.assertTrue(item["fallbackUsed"],
                                f"{rt} should mark fallbackUsed=True in mock mode")
                body = item["payload"]["body"]
                self.assertLessEqual(
                    _approx_tokens(body),
                    MAX_RECALL_OUTPUT_TOKENS * 2,
                    f"{rt} body {body!r} exceeds token cap",
                )

    # ---- 幂等性：同一 (runId, recallType) 调度两次不会重复 ----

    def test_schedule_is_idempotent(self) -> None:
        run = _make_run(user_id="u-idem")
        # 第一次调度
        first = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run.run_id, user_id="u-idem",
                                  recall_types=["d1", "d3", "d7"])
        )
        self.assertEqual(len(first), 3)
        # 第二次调度：返回已存在的 3 个，不创建新的
        second = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run.run_id, user_id="u-idem",
                                  recall_types=["d1", "d3", "d7"])
        )
        self.assertEqual(len(second), 3)
        # itemId 应一致
        first_ids = sorted(i["itemId"] for i in first)
        second_ids = sorted(i["itemId"] for i in second)
        self.assertEqual(first_ids, second_ids)

    # ---- 8 个新事件名必须存在 ----

    def test_recall_event_names_complete(self) -> None:
        """8 个新事件名（埋点）必须定义在 RECALL_EVENT_NAMES."""

        expected = {
            "recall_d1_sent", "recall_d1_opened",
            "recall_d3_sent", "recall_d3_opened",
            "recall_d7_sent", "recall_d7_opened",
            "recap_started", "recap_completed",
        }
        self.assertEqual(RECALL_EVENT_NAMES, expected)

    # ---- 周度短案：3 个 YAML 存在且 mandatory_echoes 非空 ----

    def test_three_recap_yamls_have_mandatory_echoes(self) -> None:
        import yaml
        recaps_root = Path(_PROJECT_ROOT / "content" / "case_01_revolution_street" / "recaps")
        self.assertTrue(recaps_root.is_dir(),
                        f"recaps dir missing: {recaps_root}")
        yamls = sorted(recaps_root.glob("*.yaml"))
        self.assertEqual(len(yamls), 3, f"expected 3 recaps; got {len(yamls)}")
        for y in yamls:
            raw = yaml.safe_load(y.read_text(encoding="utf-8"))
            self.assertIn("mandatory_echoes", raw)
            self.assertGreater(len(raw["mandatory_echoes"]), 0,
                               f"{y.name} has empty mandatory_echoes")
            self.assertIn("acts", raw)
            # 总时长 ≤ 5 分钟
            total = sum(a.get("duration_seconds", 0) for a in raw["acts"])
            self.assertLessEqual(total, 300,
                                 f"{y.name} exceeds 5 min ({total}s)")

    # ---- 推送内容红线：基于本局时间线 ----

    def test_push_body_never_uses_template_only(self) -> None:
        """D1 body 在没有本局时间线时不应被静默模板化."""

        # 创建一个 run 但无任何 event
        run = _make_run(user_id="u-empty")

        # 调度 D1；没有 last event，应该 fall back 到通用模板
        # Pin scheduled_for so dispatch_due fires immediately.
        self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run.run_id, user_id="u-empty",
                                  recall_types=["d1"],
                                  scheduled_for=datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(seconds=1))
        )
        self.push.dispatch_due()
        items = self.push.pull_pending(user_id="u-empty", recall_types=["d1"])
        self.assertEqual(len(items), 1)
        # 当没有 event 时，anchor 没有 keyAction；body 应明确说
        # "没有本局时间线"或类似（不假装是模板）。这里只要
        # 验证 body 不含模板化的"亲，玩家该回来看看"等空话。
        body = items[0]["payload"]["body"]
        self.assertNotIn("亲", body)
        # 也不该是 literal "[本局尚未触发任何行为]"
        # 我们的 fallback 是"你昨晚在 本局 . 那次行为..."的模板
        # 它已包含 sceneId/evidence 等字段—所以仍然是 timeline-shaped

    # ---- 端点对非法 recall_type 不创建条目 ----

    def test_schedule_ignores_invalid_recall_types(self) -> None:
        run = _make_run(user_id="u-invalid")
        items = self.recall.schedule_for_run(
            RecallScheduleRequest(run_id=run.run_id, user_id="u-invalid",
                                  recall_types=["d1", "d99", "garbage"])
        )
        # 只有 d1 应被接受
        self.assertEqual(len(items), 1)
        self.assertEqual(items[0]["recallType"], "d1")


if __name__ == "__main__":
    unittest.main()
